/**
 * Grovaitech AI Platform
 * lib/workflows/utils.ts
 *
 * Canonical Workflow Definitions and Utility Helpers.
 * Separated from Server Actions to adhere to Next.js App Router rules.
 */

import type { Workflow } from '@/types/workflows'

export const CANONICAL_DEMO_WORKFLOWS: Workflow[] = [
  {
    id: 'wf-001',
    name: 'Real Estate Lead ➔ WhatsApp & Site Visit Sync',
    description:
      'When an AI Receptionist qualifies a real estate lead and books a site visit, creates a lead record in Supabase, dispatches a WhatsApp confirmation template, and blocks the agent Google Calendar slot.',
    status: 'active',
    trigger_event: 'Lead Qualified & Site Visit Booked',
    trigger_source: 'Real Estate Lead Receptionist',
    assigned_employee: 'Real Estate Lead Receptionist',
    assigned_employee_slug: 'real-estate-lead-receptionist',
    steps: [
      { id: 's1', name: 'Insert Lead in CRM', type: 'database', target: 'Supabase real_estate_leads' },
      { id: 's2', name: 'Dispatch WhatsApp Template', type: 'whatsapp', target: '+91 Customer Phone' },
      { id: 's3', name: 'Create Calendar Event', type: 'calendar', target: 'Agent Google Calendar' },
      { id: 's4', name: 'Sync n8n Pipeline', type: 'n8n_webhook', target: 'https://n8n.grovaitech.ai/webhook/v1/real-estate' },
    ],
    n8n_webhook_url: 'https://n8n.grovaitech.ai/webhook/v1/real-estate',
    total_executions: 48,
    success_rate: 100,
    last_executed_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    created_at: '2026-07-20T00:00:00Z',
    executions: [
      {
        id: 'ex-101',
        workflow_id: 'wf-001',
        trigger_event: 'Site Visit Requested',
        status: 'success',
        started_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        duration_ms: 320,
        lead_name: 'Suresh Kumar',
        payload_summary: 'Qualified ₹1.2 Cr Villa lead in Tirupati. WhatsApp sent & calendar blocked.',
      },
      {
        id: 'ex-102',
        workflow_id: 'wf-001',
        trigger_event: 'Site Visit Requested',
        status: 'success',
        started_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        duration_ms: 285,
        lead_name: 'Ram Charan',
        payload_summary: 'Qualified ₹85 Lakh 2BHK flat lead in Nellore. Saturday site visit scheduled.',
      },
    ],
  },
  {
    id: 'wf-002',
    name: 'Clinic Appointment Booking & Reminder Pipeline',
    description:
      'Autonomous patient intake flow: confirms doctor appointment slot, writes booking record to Supabase, blocks clinic calendar, and queues a 24-hour WhatsApp reminder.',
    status: 'active',
    trigger_event: 'Appointment Booked by Patient',
    trigger_source: 'Clinic Receptionist',
    assigned_employee: 'Clinic Receptionist',
    assigned_employee_slug: 'clinic-receptionist',
    steps: [
      { id: 's1', name: 'Save Clinic Booking', type: 'database', target: 'Supabase clinic_bookings' },
      { id: 's2', name: 'Doctor Calendar Block', type: 'calendar', target: 'Dr. Verma Google Calendar' },
      { id: 's3', name: 'Queue WhatsApp 24h Reminder', type: 'whatsapp', target: 'Patient Phone' },
    ],
    n8n_webhook_url: 'https://n8n.grovaitech.ai/webhook/v1/clinic-bookings',
    total_executions: 62,
    success_rate: 98.4,
    last_executed_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    created_at: '2026-08-01T00:00:00Z',
    executions: [
      {
        id: 'ex-201',
        workflow_id: 'wf-002',
        trigger_event: 'Booking Confirmed',
        status: 'success',
        started_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        duration_ms: 410,
        lead_name: 'Priya Sharma',
        payload_summary: 'Dental consultation confirmed for Monday 10:00 AM. Dr. Verma notified.',
      },
    ],
  },
  {
    id: 'wf-003',
    name: 'Urgent Escalation ➔ Human Agent Dispatch',
    description:
      'Detects customer sentiment spikes or explicit human agent requests. Instantly pauses AI response, notifies on-duty operators via Slack, and generates a conversation summary.',
    status: 'active',
    trigger_event: 'Human Agent Requested / Sentiment Spike',
    trigger_source: 'Customer Support Agent',
    assigned_employee: 'Customer Support Agent',
    assigned_employee_slug: 'customer-support-agent',
    steps: [
      { id: 's1', name: 'Pause AI Worker Mode', type: 'ai_action', target: 'Conversation State' },
      { id: 's2', name: 'Dispatch Slack Alert', type: 'slack', target: '#support-urgent' },
      { id: 's3', name: 'SMS Duty Manager', type: 'whatsapp', target: '+91 Operations Team' },
    ],
    n8n_webhook_url: 'https://n8n.grovaitech.ai/webhook/v1/escalations',
    total_executions: 14,
    success_rate: 100,
    last_executed_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    created_at: '2026-08-10T00:00:00Z',
    executions: [
      {
        id: 'ex-301',
        workflow_id: 'wf-003',
        trigger_event: 'Human Escalation',
        status: 'success',
        started_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
        duration_ms: 195,
        lead_name: 'Lakshmi Devi',
        payload_summary: 'Customer requested human agent urgently. Slack alert dispatched to #support-urgent.',
      },
    ],
  },
  {
    id: 'wf-004',
    name: 'Inbound WhatsApp Lead Qualification Pipeline (n8n)',
    description:
      'Routes 24/7 inbound WhatsApp messages to the WhatsApp Lead Agent, parses buyer intent, syncs contacts to external CRMs via n8n webhook, and triggers follow-up drips.',
    status: 'in_development',
    trigger_event: 'New WhatsApp Inbound Message',
    trigger_source: 'WhatsApp Lead Agent',
    assigned_employee: 'WhatsApp Lead Agent',
    assigned_employee_slug: 'whatsapp-lead-agent',
    steps: [
      { id: 's1', name: 'Ingest Webhook Message', type: 'whatsapp', target: 'WhatsApp Business API' },
      { id: 's2', name: 'AI Intent Qualification', type: 'ai_action', target: 'Gemini Intent Engine' },
      { id: 's3', name: 'n8n Multi-CRM Sync Hub', type: 'n8n_webhook', target: 'n8n HubSpot/Zoho Node' },
    ],
    n8n_webhook_url: 'https://n8n.grovaitech.ai/webhook/v1/whatsapp-lead-hub',
    total_executions: 18,
    success_rate: 94.4,
    last_executed_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    created_at: '2026-08-15T00:00:00Z',
    executions: [
      {
        id: 'ex-401',
        workflow_id: 'wf-004',
        trigger_event: 'WhatsApp Inbound',
        status: 'success',
        started_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        duration_ms: 540,
        lead_name: 'Anil Reddy',
        payload_summary: 'WhatsApp inbound inquiry parsed. Intent: Real Estate Buy, Location: Tirupati.',
      },
    ],
  },
  {
    id: 'wf-005',
    name: 'AI QA Interaction Audit & Quality Scoring',
    description:
      'Nightly autonomous batch job: analyzes all completed conversation transcripts, calculates adherence scores, flags policy deviations, and compiles an executive QA report.',
    status: 'in_development',
    trigger_event: 'Conversation Completed (Batch Trigger)',
    trigger_source: 'AI QA Inspector',
    assigned_employee: 'AI QA Inspector',
    assigned_employee_slug: 'ai-qa-inspector',
    steps: [
      { id: 's1', name: 'Extract Conversation Logs', type: 'database', target: 'Supabase messages' },
      { id: 's2', name: 'Score Quality Rubric', type: 'ai_action', target: 'AI QA Evaluator' },
      { id: 's3', name: 'Generate Executive Summary', type: 'email', target: 'Management Email' },
    ],
    n8n_webhook_url: 'https://n8n.grovaitech.ai/webhook/v1/qa-audit',
    total_executions: 0,
    success_rate: 100,
    last_executed_at: 'Not executed yet',
    created_at: '2026-08-20T00:00:00Z',
    executions: [],
  },
  {
    id: 'wf-006',
    name: 'Legal Consultation Intake & Conflict Check',
    description:
      'Standardized intake pipeline for law firms: captures legal matter parameters, performs automated conflict-of-interest check, and schedules preliminary attorney consultation.',
    status: 'draft',
    trigger_event: 'New Legal Inquiry Submitted',
    trigger_source: 'Legal Intake Agent',
    assigned_employee: 'Legal Intake Agent',
    assigned_employee_slug: 'legal-intake-agent',
    steps: [
      { id: 's1', name: 'Matter Intake Form', type: 'database', target: 'Supabase legal_matters' },
      { id: 's2', name: 'Conflict of Interest Query', type: 'database', target: 'Law Firm Database' },
      { id: 's3', name: 'Schedule Consultation', type: 'calendar', target: 'Attorney Calendar' },
    ],
    n8n_webhook_url: 'https://n8n.grovaitech.ai/webhook/v1/legal-intake',
    total_executions: 0,
    success_rate: 100,
    last_executed_at: 'Not executed yet',
    created_at: '2026-08-22T00:00:00Z',
    executions: [],
  },
  {
    id: 'wf-007',
    name: 'Salon & Spa Service Booking & Reminder Pipeline',
    description:
      'Autonomous hospitality intake flow: confirms treatment/service slot, logs booking to database, reserves stylist calendar, and schedules a WhatsApp appointment confirmation.',
    status: 'active',
    trigger_event: 'Salon Service Booked by Client',
    trigger_source: 'Salon & Spa Receptionist',
    assigned_employee: 'Salon & Spa Receptionist',
    assigned_employee_slug: 'salon-spa-receptionist',
    steps: [
      { id: 's1', name: 'Save Salon Booking', type: 'database', target: 'Database Appointments' },
      { id: 's2', name: 'Stylist Calendar Block', type: 'calendar', target: 'Stylist Schedule' },
      { id: 's3', name: 'Queue WhatsApp Confirmation & Reminder', type: 'whatsapp', target: 'Client Phone' },
      { id: 's4', name: 'n8n Salon Pipeline Sync', type: 'n8n_webhook', target: 'https://n8n.grovaitech.ai/webhook/v1/salon-bookings' },
    ],
    n8n_webhook_url: 'https://n8n.grovaitech.ai/webhook/v1/salon-bookings',
    total_executions: 24,
    success_rate: 100,
    last_executed_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    created_at: '2026-08-25T00:00:00Z',
    executions: [
      {
        id: 'ex-701',
        workflow_id: 'wf-007',
        trigger_event: 'Service Booked',
        status: 'success',
        started_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        duration_ms: 380,
        lead_name: 'Ananya Roy',
        payload_summary: 'Aromatherapy Spa appointment confirmed for Saturday 3:00 PM. Stylist Maya assigned.',
      },
    ],
  },
]
