/**
 * Grovaitech AI Platform
 * app/(shell)/content/page.tsx
 *
 * Server Component for Social Media Content Hub & Human Approval Workspace.
 * Fetches durable packages and posts from Supabase (with resilient fallback)
 * and passes typed data to the client ContentHubWorkspace.
 */

import { getContentHubData } from '@/app/actions/content'
import ContentHubWorkspace from '@/components/content/ContentHubWorkspace'

export const metadata = {
  title: 'Social Media Content Hub | Grovaitech',
  description:
    'Audit, refine, approve, and schedule platform-tailored content generated by your Social Media Marketing AI Employee.',
}

export default async function ContentHubPage() {
  const result = await getContentHubData()

  return (
    <ContentHubWorkspace
      initialPackages={result.packages}
      initialPosts={result.posts}
      initialOverview={result.overview}
      isFallback={result.isFallback}
    />
  )
}
